---
- hosts: all
  become: yes
  tasks:
    - name: Remove old Docker GPG key if it exists
      ansible.builtin.file:
        path: /etc/apt/keyrings/docker.gpg
        state: absent

    - name: Remove old Docker repository source file if it exists
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent

    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - git
          - python3
          - python3-pip
        state: present
        update_cache: yes
    
    # Use a command to install the GPG key directly, which is more reliable
    - name: Install Docker's official GPG key via command
      ansible.builtin.shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        sudo chmod a+r /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg
    
    # Add Docker repository to APT sources
    - name: Add Docker repository to APT sources
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
        
    - name: Update apt cache before installing Docker
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Install Harness Delegate (Docker-based)
      ansible.builtin.shell: |
        docker run  -d --cpus=1 --memory=2g \
          -e DELEGATE_NAME=docker-reethu \
          -e NEXT_GEN="true" \
          -e DELEGATE_TYPE="DOCKER" \
          -e ACCOUNT_ID=ucHySz2jQKKWQweZdXyCog \
          -e DELEGATE_TOKEN=NTRhYTY0Mjg3NThkNjBiNjMzNzhjOGQyNjEwOTQyZjY= \
          -e DELEGATE_TAGS="" \
          -e MANAGER_HOST_AND_PORT=https://app.harness.io us-docker.pkg.dev/gar-prod-setup/harness-public/harness/delegate:25.07.86401
